### ISSUE TITLE
Add `order` parameter to paginator

### ISSUE THREAD

**Issue by adriano66** [tf2pickup-org/server-legacy#3]
Hey, could you add `order` param to paginator so API user could fetch results in reverse order to cache older results and reduce number of API calls this way?
https://github.com/tf2pickup-pl/server/blob/master/src/games/controllers/game-controller.ts#L16

**Comment by garrappachc** [comment]
That's a great idea. I'll try to do it as soon as I can.

**Comment by garrappachc** [comment]
This change does not break the API, thus it'll go live tonight for api.tf2pickup.pl.
Just for clarification: the parameter is not called `order`. It is named `sort` and accepts, as for now, two values: `-launched_at` (default) and `launched_at`. The latter one sorts games by their launch date, ascending.

**Comment by adriano66** [comment]
Cool, thanks
